api_hash: your_api_hash
api_id: your_api_id
chat_id:
download_directory:
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: {}
last_read_message_id: {}
media_types:
- audio
- photo
- video
- document
- voice
- video_note
phone_number:
